### ISSUE TITLE
update DNA file to support Kalliope v0.5.0

### ISSUE THREAD

**Issue by Sispheor** [bacardi55/kalliope-domoticz#1]
We've update the major release of Kalliope to v0.5.0 due to the breaking changes we made by adding hook feature.
You just need to add the new tag to your DNA file [like here](https://github.com/kalliope-project/kalliope_neuron_slack/commit/f76d829e7fd3ad95f8adb2ea7045b7ea2c859584).

**Comment by bacardi55** [comment]
Fix via 5fb1c29503bc5a688ae4488e3649cb5736f5f23e
Thanks
